create table public.blog_posts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title character varying null,
  content text null,
  constraint blog_posts_pkey primary key (id)
) TABLESPACE pg_default;