create table public.portfolio_projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  priority integer null default 1,
  url text null,
  title text null,
  description text null,
  constraint portfolio_projects_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO public.portfolio_projects (title, url, description, priority)
VALUES ('My GitHub', 'https://github.com/amarkules1', 'Check out my other projects on GitHub.', 1);